# ============================================================================
# HOME ASSISTANT AUTOMATIONS - Gazebo Stove Schedule (FIXED)
# ============================================================================
# Priority 3: Schedule (Home Mode Time / Away Mode Time)
#
# IMPORTANT: These automations ONLY change Presence Mode
# They do NOT affect Force Off or Emergency Heat switches
#
# ============================================================================
# AUTOMATION 1: Set Home Mode at Scheduled Time
# ============================================================================

- alias: "Gazebo: Set Home Mode at Time"
  description: "Automatically set presence to home at configured time (Priority 3: Schedule)"
  trigger:
    - platform: time
      at: input_datetime.home_mode_time
  condition:
    # Only run if schedule is enabled (if you have this switch)
    # Remove this condition if you don't have input_boolean.gazebo_schedule_enabled
    - condition: state
      entity_id: input_boolean.gazebo_schedule_enabled
      state: "on"
  action:
    - service: select.select_option
      target:
        entity_id: select.gazebo_stove_presence_mode
      data:
        option: "home"
    - service: system_log.write
      data:
        level: info
        message: "Gazebo: Automatic home mode enabled at {{ now().strftime('%H:%M') }}"
  mode: single

# ============================================================================
# AUTOMATION 2: Set Away Mode at Scheduled Time
# ============================================================================

- alias: "Gazebo: Set Away Mode at Time"
  description: "Automatically set presence to away at configured time (Priority 3: Schedule)"
  trigger:
    - platform: time
      at: input_datetime.away_mode_time
  condition:
    # Only run if schedule is enabled (if you have this switch)
    # Remove this condition if you don't have input_boolean.gazebo_schedule_enabled
    - condition: state
      entity_id: input_boolean.gazebo_schedule_enabled
      state: "on"
  action:
    - service: select.select_option
      target:
        entity_id: select.gazebo_stove_presence_mode
      data:
        option: "away"
    - service: system_log.write
      data:
        level: info
        message: "Gazebo: Automatic away mode enabled at {{ now().strftime('%H:%M') }}"
  mode: single

# ============================================================================
# NOTE: These automations do NOT:
# - Turn on Force Off switch
# - Turn off Force Off switch
# - Control Emergency Heat switch
# - Control the relay directly
#
# They ONLY change Presence Mode (home/away)
# The ESPHome device handles all relay control based on priority logic
# ============================================================================

