# ============================================================================
# CORE ESPHOME CONFIGURATION
# ============================================================================
# Board configuration, WiFi, API, OTA, NTP, Logging

esphome:
  name: gazebo-stove
  friendly_name: Gazebo Stove Heating Control
  on_boot:
    priority: 600
    then:
      - logger.log: "GazeboWx starting up..."
      - wait_until:
          condition:
            wifi.connected:
          timeout: 30s
      - logger.log: "WiFi connected, initializing components"

# ============================================================================
# BOARD SELECTION & CONFIGURATION
# ============================================================================

esp32:
  board: esp32doit-devkit-v1
  variant: esp32
  framework:
    type: arduino

# ============================================================================
# LOGGING & DEBUGGING
# ============================================================================

logger:
  level: DEBUG
  logs:
    uart.debug: DEBUG
    component: DEBUG
    sensor: DEBUG
    template.number: DEBUG

# ============================================================================
# WIFI CONFIGURATION
# ============================================================================

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Gazebo-WX Fallback"
    password: "gazebo1234"

mdns:
  disabled: false

# ============================================================================
# HOME ASSISTANT INTEGRATION
# ============================================================================

api:
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password

# ============================================================================
# NETWORK TIME PROTOCOL (NTP)
# ============================================================================

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 0.ca.pool.ntp.org
      - 1.ca.pool.ntp.org
      - 2.ca.pool.ntp.org
    timezone: America/Toronto
    on_time_sync:
      then:
        - logger.log: "Time synced from NTP"
