# ============================================================================
# CORE ESPHOME CONFIGURATION
# ============================================================================
# Board configuration, WiFi, API, OTA, NTP, Logging

# ============================================================================
# SENSOR TYPE SELECTION
# ============================================================================
# Choose temperature sensor: 'dht22' or 'ds18b20'
# DHT22: Measures both temperature and humidity (single GPIO pin)
# DS18B20: Temperature only via OneWire (humidity imported from Home Assistant)
substitutions:
  sensor_type: "dht22"  # Options: "dht22" or "ds18b20"
  sensor_pin: "GPIO4"     # GPIO pin for the sensor

esphome:
  name: gazebo-stove
  friendly_name: Gazebo Stove Heating Control
  on_boot:
    priority: 600
    then:
      - logger.log: "GazeboWx starting up..."
      - wait_until:
          condition:
            wifi.connected:
          timeout: 30s
      - logger.log: "WiFi connected, initializing components"
      - script.execute: init_nextion

# ============================================================================
# BOARD SELECTION & CONFIGURATION
# ============================================================================

esp32:
  board: esp32doit-devkit-v1
  variant: esp32
  framework:
    type: arduino

# ============================================================================
# LOGGING & DEBUGGING
# ============================================================================

logger:
  level: INFO
  logs:
    # Reduce log verbosity to prevent API connection overload
    # Set to DEBUG only when troubleshooting specific issues
    uart.debug: INFO
    component: WARN
    sensor: WARN
    # Keep important components at INFO level
    schedule: INFO
    heating: INFO
    priority: INFO

# ============================================================================
# WIFI CONFIGURATION
# ============================================================================

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Gazebo-WX Fallback"
    password: "gazebo1234"

mdns:
  disabled: false

# ============================================================================
# HOME ASSISTANT INTEGRATION
# ============================================================================

api:
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password

# ============================================================================
# NETWORK TIME PROTOCOL (NTP)
# ============================================================================

time:
  - platform: sntp
    id: sntp_time
    servers:
      - time.google.com
      - time.cloudflare.com
      - 0.pool.ntp.org
    timezone: America/Edmonton
    on_time_sync:
      then:
        - logger.log: "Time synced from NTP"
