# ============================================================================
# ENTITIES - User Configuration & Status
# ============================================================================
# Number sliders, select dropdowns, binary sensors, and text sensors

# ============================================================================
# BINARY SENSORS - Status & Alarms
# ============================================================================

binary_sensor:
  # Sensor Malfunction Alarm
  - platform: template
    name: "Sensor Malfunction"
    id: sensor_malfunction
    icon: "mdi:alert-circle"
    device_class: problem
    lambda: |-
      return id(bad_read_count) > 10;

# ============================================================================
# NUMBER ENTITIES - User Configuration
# ============================================================================

number:

  # Temperature Offset (Calibration)
  - platform: template
    name: "Temperature Offset"
    id: temp_offset
    min_value: -5
    max_value: 5
    step: 0.1
    unit_of_measurement: "째C"
    icon: "mdi:plus-minus"
    entity_category: "diagnostic"
    restore_value: yes
    optimistic: true
    initial_value: 0
    set_action:
      then:
        - logger.log:
            format: "Temperature offset set to %.1f째C"
            args: ["x"]

# ============================================================================
# SELECT ENTITIES - Mode Selection
# ============================================================================

select:
  # Presence Mode
  - platform: template
    name: "Presence Mode"
    id: presence_mode
    options:
      - "home"
      - "away"
    initial_option: "home"
    restore_value: true
    optimistic: true
    set_action:
      then:
        - logger.log:
            format: "Presence mode set to: %s"
            args: ["x.c_str()"]
        # Sync Thermostat Preset and Mode with Presence Mode
        - if:
            condition:
              lambda: 'return x == "away";'
            then:
              # User wants explicit "OFF" in UI
              - climate.control:
                  id: gazebo_thermostat
                  mode: "OFF"
            else:
              # Restore Heating in Home mode
              - climate.control:
                  id: gazebo_thermostat
                  mode: "HEAT"
                  preset: Home
        # Re-evaluate heating when presence changes
        - script.execute: manage_heating

# ============================================================================
# SWITCH ENTITIES - Manual Overrides
# ============================================================================
# Note: Manual Run and Manual Stop switches are now defined in hardware.yaml
# This prevents YAML section conflicts when merging multiple includes

# ============================================================================
# TEXT SENSORS - Status Messages & Information
# ============================================================================

text_sensor:
  # WiFi Information
  - platform: wifi_info
    ip_address:
      name: "Device IP Address"
      id: device_ip
      entity_category: "diagnostic"
    ssid:
      name: "WiFi SSID"
      id: wifi_ssid
      entity_category: "diagnostic"
    mac_address:
      name: "MAC Address"
      entity_category: "diagnostic"
    bssid:
      name: "WiFi BSSID"
      entity_category: "diagnostic"

  # System Status Message
  - platform: template
    name: "System Status"
    id: system_status
    update_interval: 10s
    lambda: |-
      if (id(sensor_malfunction).state) {
        return std::string("ALARM: Sensor Malfunction");
      } else if (!id(gazebo_nextion).is_failed()) {
        return std::string("OK - Nextion Connected");
      } else {
        return std::string("OK - Display Offline");
      }

  # Heating Status
  - platform: template
    name: "Heating Status"
    id: heating_status
    icon: "mdi:power"

# ============================================================================
# DATETIME ENTITIES - Schedule Times (24-hour format)
# ============================================================================
# Note: Entity IDs use numbering (1, 2) to ensure Home appears before Away
# in Home Assistant UI (alphabetical sorting by entity_id)

datetime:
  # Home Mode Start Time (24-hour format time picker)
  - platform: template
    type: time
    name: "Home Time (24h)"
    id: schedule_1_home
    icon: "mdi:home-clock"
    optimistic: yes
    initial_value: "06:00:00"
    restore_value: true

  # Away Mode Start Time (24-hour format time picker)
  - platform: template
    type: time
    name: "Away Time (24h)"
    id: schedule_2_away
    icon: "mdi:clock-outline"
    optimistic: yes
    initial_value: "22:00:00"
    restore_value: true

# ============================================================================
# GLOBAL VARIABLES - Internal State Tracking
# ============================================================================

globals:
  # Bad temperature read counter
  - id: bad_read_count
    type: int
    restore_value: no
    initial_value: '0'

  # Manual run timeout timestamp
  - id: manual_run_timeout
    type: long
    restore_value: no
    initial_value: '0'

  # Manual run state tracker
  - id: manual_run_active
    type: bool
    restore_value: no
    initial_value: 'false'

  # Manual stop state tracker
  - id: manual_stop_active
    type: bool
    restore_value: no
    initial_value: 'false'

  # Nextion Slider0 value tracker (0-100 maps to 15-30째C)
  - id: nextion_slider_value
    type: float
    restore_value: no
    initial_value: '33.3'  # Default to 20째C = (20-15)/15*100 = 33.3

  # Slider touch release flag
  - id: slider_touched
    type: bool
    restore_value: no
    initial_value: 'false'

  # Heater output level tracker (0.0 to 1.0)
  # Used to track slow_pwm output since it doesn't have get_state()
  - id: heater_output_level
    type: float
    restore_value: no
    initial_value: '0.0'

  # Heating action flag for priority system
  # 0=PID, 1=ForceOff, 2=EmergencyHeat, 3=Standby
  - id: heating_action
    type: int
    restore_value: no
    initial_value: '0'

  # Test Icon ID for finding correct weather icons
  - id: test_icon_id
    type: int
    restore_value: no
    initial_value: '0'

  # Nextion display ready flag - prevents early sends before init
  - id: nextion_ready
    type: bool
    restore_value: no
    initial_value: 'false'
