# ============================================================================
# WEATHER DATA INTEGRATION (Open-Meteo via Home Assistant)
# ============================================================================
# Imports weather forecast data from Home Assistant's Open-Meteo integration
# and displays it on Nextion Pages 1 (hourly) and 2 (daily)

# ============================================================================
# HOME ASSISTANT SENSOR IMPORTS - Hourly Forecast (Page 1)
# ============================================================================
# NOTE: ESPHome requires explicit sensor definitions - YAML cannot loop/iterate
# Each forecast hour (0-6) needs 3 sensors: feels_like, precipitation, weather_code
# Each forecast day (0-6) needs 3 sensors: temp_max, precipitation, weather_code
# Total: 42 sensors (21 hourly + 21 daily)

sensor:
  # Hour 0 (Current hour)
  - platform: homeassistant
    id: ha_hour_0_feels_like
    entity_id: sensor.gazebo_hour_0_feels_like
    internal: true


  - platform: homeassistant
    id: ha_hour_0_precipitation
    entity_id: sensor.gazebo_hour_0_precipitation
    internal: true
    
  - platform: homeassistant
    id: ha_hour_0_weather_code
    entity_id: sensor.gazebo_hour_0_weather_code
    internal: true

  # Hour 1
  - platform: homeassistant
    id: ha_hour_1_feels_like
    entity_id: sensor.gazebo_hour_1_feels_like
    internal: true
    
  - platform: homeassistant
    id: ha_hour_1_precipitation
    entity_id: sensor.gazebo_hour_1_precipitation
    internal: true
    
  - platform: homeassistant
    id: ha_hour_1_weather_code
    entity_id: sensor.gazebo_hour_1_weather_code
    internal: true

  # Hour 2
  - platform: homeassistant
    id: ha_hour_2_feels_like
    entity_id: sensor.gazebo_hour_2_feels_like
    internal: true
    
  - platform: homeassistant
    id: ha_hour_2_precipitation
    entity_id: sensor.gazebo_hour_2_precipitation
    internal: true
    
  - platform: homeassistant
    id: ha_hour_2_weather_code
    entity_id: sensor.gazebo_hour_2_weather_code
    internal: true

  # Hour 3
  - platform: homeassistant
    id: ha_hour_3_feels_like
    entity_id: sensor.gazebo_hour_3_feels_like
    internal: true
    
  - platform: homeassistant
    id: ha_hour_3_precipitation
    entity_id: sensor.gazebo_hour_3_precipitation
    internal: true
    
  - platform: homeassistant
    id: ha_hour_3_weather_code
    entity_id: sensor.gazebo_hour_3_weather_code
    internal: true

  # Hour 4
  - platform: homeassistant
    id: ha_hour_4_feels_like
    entity_id: sensor.gazebo_hour_4_feels_like
    internal: true
    
  - platform: homeassistant
    id: ha_hour_4_precipitation
    entity_id: sensor.gazebo_hour_4_precipitation
    internal: true
    
  - platform: homeassistant
    id: ha_hour_4_weather_code
    entity_id: sensor.gazebo_hour_4_weather_code
    internal: true

  # Hour 5
  - platform: homeassistant
    id: ha_hour_5_feels_like
    entity_id: sensor.gazebo_hour_5_feels_like
    internal: true
    
  - platform: homeassistant
    id: ha_hour_5_precipitation
    entity_id: sensor.gazebo_hour_5_precipitation
    internal: true
    
  - platform: homeassistant
    id: ha_hour_5_weather_code
    entity_id: sensor.gazebo_hour_5_weather_code
    internal: true

  # Hour 6
  - platform: homeassistant
    id: ha_hour_6_feels_like
    entity_id: sensor.gazebo_hour_6_feels_like
    internal: true
    
  - platform: homeassistant
    id: ha_hour_6_precipitation
    entity_id: sensor.gazebo_hour_6_precipitation
    internal: true
    
  - platform: homeassistant
    id: ha_hour_6_weather_code
    entity_id: sensor.gazebo_hour_6_weather_code
    internal: true

  # ============================================================================
  # HOME ASSISTANT SENSOR IMPORTS - Daily Forecast (Page 2)
  # ============================================================================

  # Day 0 (Today)
  - platform: homeassistant
    id: ha_day_0_temp_max
    entity_id: sensor.gazebo_day_0_temperature_max
    internal: true
    
  - platform: homeassistant
    id: ha_day_0_precipitation
    entity_id: sensor.gazebo_day_0_precipitation_probability
    internal: true
    
  - platform: homeassistant
    id: ha_day_0_weather_code
    entity_id: sensor.gazebo_day_0_weather_code
    internal: true

  # Day 1
  - platform: homeassistant
    id: ha_day_1_temp_max
    entity_id: sensor.gazebo_day_1_temperature_max
    internal: true
    
  - platform: homeassistant
    id: ha_day_1_precipitation
    entity_id: sensor.gazebo_day_1_precipitation_probability
    internal: true
    
  - platform: homeassistant
    id: ha_day_1_weather_code
    entity_id: sensor.gazebo_day_1_weather_code
    internal: true

  # Day 2
  - platform: homeassistant
    id: ha_day_2_temp_max
    entity_id: sensor.gazebo_day_2_temperature_max
    internal: true
    
  - platform: homeassistant
    id: ha_day_2_precipitation
    entity_id: sensor.gazebo_day_2_precipitation_probability
    internal: true
    
  - platform: homeassistant
    id: ha_day_2_weather_code
    entity_id: sensor.gazebo_day_2_weather_code
    internal: true

  # Day 3
  - platform: homeassistant
    id: ha_day_3_temp_max
    entity_id: sensor.gazebo_day_3_temperature_max
    internal: true
    
  - platform: homeassistant
    id: ha_day_3_precipitation
    entity_id: sensor.gazebo_day_3_precipitation_probability
    internal: true
    
  - platform: homeassistant
    id: ha_day_3_weather_code
    entity_id: sensor.gazebo_day_3_weather_code
    internal: true

  # Day 4
  - platform: homeassistant
    id: ha_day_4_temp_max
    entity_id: sensor.gazebo_day_4_temperature_max
    internal: true
    
  - platform: homeassistant
    id: ha_day_4_precipitation
    entity_id: sensor.gazebo_day_4_precipitation_probability
    internal: true
    
  - platform: homeassistant
    id: ha_day_4_weather_code
    entity_id: sensor.gazebo_day_4_weather_code
    internal: true

  # Day 5
  - platform: homeassistant
    id: ha_day_5_temp_max
    entity_id: sensor.gazebo_day_5_temperature_max
    internal: true
    
  - platform: homeassistant
    id: ha_day_5_precipitation
    entity_id: sensor.gazebo_day_5_precipitation_probability
    internal: true
    
  - platform: homeassistant
    id: ha_day_5_weather_code
    entity_id: sensor.gazebo_day_5_weather_code
    internal: true

  # Day 6
  - platform: homeassistant
    id: ha_day_6_temp_max
    entity_id: sensor.gazebo_day_6_temperature_max
    internal: true
    
  - platform: homeassistant
    id: ha_day_6_precipitation
    entity_id: sensor.gazebo_day_6_precipitation_probability
    internal: true
    
  - platform: homeassistant
    id: ha_day_6_weather_code
    entity_id: sensor.gazebo_day_6_weather_code
    internal: true

# ============================================================================
# WEATHER UPDATE SCRIPTS
# ============================================================================

script:
  # Update Page 1 (Hourly Forecast - Ressentie)
  - id: update_nextion_hourly
    then:
      - lambda: |-
          ESP_LOGI("WEATHER", "Starting hourly forecast update...");
          if (id(gazebo_nextion).is_failed()) {
            ESP_LOGW("WEATHER", "Nextion failed, skipping hourly update");
            return;
          }
          
          // Debug: Log first sensor value
          ESP_LOGI("WEATHER", "HA Sensor dt0 feels_like: %.1f", id(ha_hour_0_feels_like).state);

          // WMO code to Nextion icon ID mapping
          // NOTE: This function is duplicated in update_nextion_daily below
          // ESPHome lambdas cannot share functions across scripts
          auto wmo_to_icon = [](int wmo) -> int {
            // Mapping based on user provided Nextion Picture IDs
            if (wmo == 0) return 26;          // Clear sky -> Sunny
            if (wmo == 1) return 26;          // Mainly clear -> Sunny
            if (wmo == 2) return 22;          // Partly cloudy -> Partially cloudy
            if (wmo == 3) return 6;           // Overcast -> Cloudy
            if (wmo == 45 || wmo == 48) return 6; // Fog -> Cloudy (Fallback)
            
            if (wmo >= 51 && wmo <= 55) return 14; // Drizzle -> Light Rain
            if (wmo == 56 || wmo == 57) return 11; // Freezing Drizzle -> Freezing Rain
            
            if (wmo == 61 || wmo == 63) return 14; // Rain Slight/Mod -> Light Rain
            if (wmo == 65) return 15;              // Rain Heavy -> Heavy Rain
            if (wmo == 66 || wmo == 67) return 11; // Freezing Rain -> Freezing Rain
            
            if (wmo == 71 || wmo == 73) return 19; // Snow Slight/Mod -> Light Snow
            if (wmo == 75) return 20;              // Snow Heavy -> Heavy Snow
            if (wmo == 77) return 19;              // Snow Grains -> Light Snow
            
            if (wmo == 80 || wmo == 81) return 14; // Rain Showers Sl/Mod -> Light Rain
            if (wmo == 82) return 15;              // Rain Showers Violent -> Heavy Rain
            
            if (wmo == 85) return 19;              // Snow Showers Slight -> Light Snow
            if (wmo == 86) return 20;              // Snow Showers Heavy -> Heavy Snow
            
            if (wmo >= 95) return 7;               // Thunderstorm -> Thunderstorm
            
            return 26; // Default to Sunny
          };
          
          // Get current hour for time labels
          auto time_now = id(sntp_time).now();
          if (!time_now.is_valid()) {
            ESP_LOGW("WEATHER", "Time not valid yet, skipping");
            return;
          }
          int current_hour = time_now.hour;
          
          // Helper to safely send value or skip if NaN
          auto send_if_valid = [&](const char* component, float value) {
            if (!isnan(value)) {
              id(gazebo_nextion).send_command_printf("%s=%d", component, (int)value);
            }
          };

          // Hour 0
          id(gazebo_nextion).send_command_printf("one.dt0.val=%d", current_hour);
          send_if_valid("one.fl0.val", id(ha_hour_0_feels_like).state);
          send_if_valid("one.rain0.val", id(ha_hour_0_precipitation).state);
          send_if_valid("one.wxIcon0.pic", wmo_to_icon((int)id(ha_hour_0_weather_code).state));
          
          // Hour 1
          id(gazebo_nextion).send_command_printf("one.dt1.val=%d", (current_hour + 1) % 24);
          send_if_valid("one.fl1.val", id(ha_hour_1_feels_like).state);
          send_if_valid("one.rain1.val", id(ha_hour_1_precipitation).state);
          send_if_valid("one.wxIcon1.pic", wmo_to_icon((int)id(ha_hour_1_weather_code).state));
          
          // Hour 2
          id(gazebo_nextion).send_command_printf("one.dt2.val=%d", (current_hour + 2) % 24);
          send_if_valid("one.fl2.val", id(ha_hour_2_feels_like).state);
          send_if_valid("one.rain2.val", id(ha_hour_2_precipitation).state);
          send_if_valid("one.wxIcon2.pic", wmo_to_icon((int)id(ha_hour_2_weather_code).state));
          
          // Hour 3
          id(gazebo_nextion).send_command_printf("one.dt3.val=%d", (current_hour + 3) % 24);
          send_if_valid("one.fl3.val", id(ha_hour_3_feels_like).state);
          send_if_valid("one.rain3.val", id(ha_hour_3_precipitation).state);
          send_if_valid("one.wxIcon3.pic", wmo_to_icon((int)id(ha_hour_3_weather_code).state));
          
          // Hour 4
          id(gazebo_nextion).send_command_printf("one.dt4.val=%d", (current_hour + 4) % 24);
          send_if_valid("one.fl4.val", id(ha_hour_4_feels_like).state);
          send_if_valid("one.rain4.val", id(ha_hour_4_precipitation).state);
          send_if_valid("one.wxIcon4.pic", wmo_to_icon((int)id(ha_hour_4_weather_code).state));
          
          // Hour 5
          id(gazebo_nextion).send_command_printf("one.dt5.val=%d", (current_hour + 5) % 24);
          send_if_valid("one.fl5.val", id(ha_hour_5_feels_like).state);
          send_if_valid("one.rain5.val", id(ha_hour_5_precipitation).state);
          send_if_valid("one.wxIcon5.pic", wmo_to_icon((int)id(ha_hour_5_weather_code).state));
          
          // Hour 6
          id(gazebo_nextion).send_command_printf("one.dt6.val=%d", (current_hour + 6) % 24);
          send_if_valid("one.fl6.val", id(ha_hour_6_feels_like).state);
          send_if_valid("one.rain6.val", id(ha_hour_6_precipitation).state);
          send_if_valid("one.wxIcon6.pic", wmo_to_icon((int)id(ha_hour_6_weather_code).state));
          
          ESP_LOGI("WEATHER", "Updated hourly forecast on Page 1");

  # Update Page 2 (Daily Forecast - Prévisions)
  - id: update_nextion_daily
    then:
      - lambda: |-
          if (id(gazebo_nextion).is_failed()) {
            ESP_LOGW("WEATHER", "Nextion failed, skipping daily update");
            return;
          }
          
          // WMO code to Nextion icon ID mapping
          // NOTE: Duplicated from update_nextion_hourly - ESPHome lambdas cannot share functions
          auto wmo_to_icon = [](int wmo) -> int {
            // Mapping based on user provided Nextion Picture IDs
            if (wmo == 0) return 26;          // Clear sky -> Sunny
            if (wmo == 1) return 26;          // Mainly clear -> Sunny
            if (wmo == 2) return 22;          // Partly cloudy -> Partially cloudy
            if (wmo == 3) return 6;           // Overcast -> Cloudy
            if (wmo == 45 || wmo == 48) return 6; // Fog -> Cloudy (Fallback)
            
            if (wmo >= 51 && wmo <= 55) return 14; // Drizzle -> Light Rain
            if (wmo == 56 || wmo == 57) return 11; // Freezing Drizzle -> Freezing Rain
            
            if (wmo == 61 || wmo == 63) return 14; // Rain Slight/Mod -> Light Rain
            if (wmo == 65) return 15;              // Rain Heavy -> Heavy Rain
            if (wmo == 66 || wmo == 67) return 11; // Freezing Rain -> Freezing Rain
            
            if (wmo == 71 || wmo == 73) return 19; // Snow Slight/Mod -> Light Snow
            if (wmo == 75) return 20;              // Snow Heavy -> Heavy Snow
            if (wmo == 77) return 19;              // Snow Grains -> Light Snow
            
            if (wmo == 80 || wmo == 81) return 14; // Rain Showers Sl/Mod -> Light Rain
            if (wmo == 82) return 15;              // Rain Showers Violent -> Heavy Rain
            
            if (wmo == 85) return 19;              // Snow Showers Slight -> Light Snow
            if (wmo == 86) return 20;              // Snow Showers Heavy -> Heavy Snow
            
            if (wmo >= 95) return 7;               // Thunderstorm -> Thunderstorm
            
            return 26; // Default to Sunny
          };
          
          auto time_now = id(sntp_time).now();
          if (!time_now.is_valid()) {
            ESP_LOGW("WEATHER", "Time not valid yet, skipping");
            return;
          }
          int today = time_now.day_of_week - 1;  // 0=Sunday
          
          // Helper to safely send value or skip if NaN
          auto send_if_valid = [&](const char* component, float value) {
            if (!isnan(value)) {
              id(gazebo_nextion).send_command_printf("%s=%d", component, (int)value);
            }
          };

          // Day 0 (Today)
          int d0 = time_now.day_of_month;
          float t0_f = id(ha_day_0_temp_max).state;
          float p0_f = id(ha_day_0_precipitation).state;
          int i0 = wmo_to_icon((int)id(ha_day_0_weather_code).state);
          ESP_LOGI("WEATHER_DBG", "Day0: dt=%d temp=%.1f precip=%.1f icon=%d", d0, t0_f, p0_f, i0);
          
          id(gazebo_nextion).send_command_printf("two.dt10.val=%d", d0);
          send_if_valid("two.temp0.val", id(ha_day_0_temp_max).state);
          send_if_valid("two.precip0.val", id(ha_day_0_precipitation).state);
          send_if_valid("two.wxIcon10.pic", wmo_to_icon((int)id(ha_day_0_weather_code).state));
          
          // Day 1
          time_t t1 = time_now.timestamp + 86400;
          struct tm *tm1 = localtime(&t1);
          int d1 = tm1->tm_mday;
          
          id(gazebo_nextion).send_command_printf("two.dt11.val=%d", d1);
          send_if_valid("two.temp1.val", id(ha_day_1_temp_max).state);
          send_if_valid("two.precip1.val", id(ha_day_1_precipitation).state);
          send_if_valid("two.wxIcon11.pic", wmo_to_icon((int)id(ha_day_1_weather_code).state));
          
          // Day 2
          time_t t2 = time_now.timestamp + 172800;
          struct tm *tm2 = localtime(&t2);
          id(gazebo_nextion).send_command_printf("two.dt12.val=%d", tm2->tm_mday);
          send_if_valid("two.temp2.val", id(ha_day_2_temp_max).state);
          send_if_valid("two.precip2.val", id(ha_day_2_precipitation).state);
          send_if_valid("two.wxIcon12.pic", wmo_to_icon((int)id(ha_day_2_weather_code).state));
          
          // Day 3
          time_t t3 = time_now.timestamp + 259200;
          struct tm *tm3 = localtime(&t3);
          id(gazebo_nextion).send_command_printf("two.dt13.val=%d", tm3->tm_mday);
          send_if_valid("two.temp3.val", id(ha_day_3_temp_max).state);
          send_if_valid("two.precip3.val", id(ha_day_3_precipitation).state);
          send_if_valid("two.wxIcon13.pic", wmo_to_icon((int)id(ha_day_3_weather_code).state));
          
          // Day 4
          time_t t4 = time_now.timestamp + 345600;
          struct tm *tm4 = localtime(&t4);
          id(gazebo_nextion).send_command_printf("two.dt14.val=%d", tm4->tm_mday);
          send_if_valid("two.temp4.val", id(ha_day_4_temp_max).state);
          send_if_valid("two.precip4.val", id(ha_day_4_precipitation).state);
          send_if_valid("two.wxIcon14.pic", wmo_to_icon((int)id(ha_day_4_weather_code).state));
          
          // Day 5
          time_t t5 = time_now.timestamp + 432000;
          struct tm *tm5 = localtime(&t5);
          id(gazebo_nextion).send_command_printf("two.dt15.val=%d", tm5->tm_mday);
          send_if_valid("two.temp5.val", id(ha_day_5_temp_max).state);
          send_if_valid("two.precip5.val", id(ha_day_5_precipitation).state);
          send_if_valid("two.wxIcon15.pic", wmo_to_icon((int)id(ha_day_5_weather_code).state));
          
          // Day 6
          time_t t6 = time_now.timestamp + 518400;
          struct tm *tm6 = localtime(&t6);
          id(gazebo_nextion).send_command_printf("two.dt16.val=%d", tm6->tm_mday);
          send_if_valid("two.temp6.val", id(ha_day_6_temp_max).state);
          send_if_valid("two.precip6.val", id(ha_day_6_precipitation).state);
          send_if_valid("two.wxIcon16.pic", wmo_to_icon((int)id(ha_day_6_weather_code).state));
          
          ESP_LOGI("WEATHER", "Updated daily forecast on Page 2");

# ============================================================================
# WEATHER UPDATE INTERVAL - Refresh forecasts every 30 minutes
# ============================================================================

interval:
  - interval: 30min
    then:
      - script.execute: update_nextion_hourly
      - script.execute: update_nextion_daily
